[tempest-extras]Add barbican tempest plugin
The whitebox tempest plugin actually depends on the barbican tempest
plugin otherwise the vTPM tests are failing with

    cls.os_primary.secrets_client = service_clients.secret_v1.SecretClient(
AttributeError: 'ServiceClients' object has no attribute 'secret_v1'

So this patch adding it.